-- CREARE USER SPECIAL PT PROIECT

CREATE USER USER_SECURITATE
IDENTIFIED BY 1234;

-- ACORDAM DREPTURI

GRANT CONNECT, RESOURCE TO USER_SECURITATE;

ALTER USER USER_SECURITATE
QUOTA UNLIMITED ON USERS;

SELECT username
FROM dba_users
WHERE username='USER_SECURITATE';

GRANT CREATE VIEW TO USER_SECURITATE;
GRANT CREATE SYNONYM TO USER_SECURITATE;

--pt criptare
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO USER_SECURITATE;


--pt auditare
GRANT EXECUTE ON SYS.DBMS_FGA TO USER_SECURITATE;