-- Creare utilizator pentru managementul lucrărilor și clienților
CREATE USER USER_MANAGER
IDENTIFIED BY 1234;

-- Creare utilizator pentru departamentul HR
CREATE USER USER_HR
IDENTIFIED BY 1234;

-- Creare utilizator pentru departamentul Logistică
CREATE USER USER_LOGISTICA
IDENTIFIED BY 1234;

-- Acordare drept de conectare
GRANT CONNECT TO USER_MANAGER;
GRANT CONNECT TO USER_HR;
GRANT CONNECT TO USER_LOGISTICA;
-- Acordare spațiu în tablespace
ALTER USER USER_MANAGER QUOTA UNLIMITED ON USERS;
ALTER USER USER_HR QUOTA UNLIMITED ON USERS;
ALTER USER USER_LOGISTICA QUOTA UNLIMITED ON USERS;

-- USER_MANAGER gestionează CLIENT, LUCRARE, LOCATIE, FACTURA, OFERTA, RECENZIE
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.CLIENT TO USER_MANAGER;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.LUCRARE TO USER_MANAGER;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.LOCATIE TO USER_MANAGER;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.FACTURA TO USER_MANAGER;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.OFERTA TO USER_MANAGER;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.RECENZIE TO USER_MANAGER;

-- USER_HR gestionează ANGAJAT, SEF, ECHIPA
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.ANGAJAT TO USER_HR;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.SEF TO USER_HR;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.ECHIPA TO USER_HR;

-- USER_LOGISTICA gestionează UTILAJ, PROGRAMARE_UTILAJE, COLABORATORI, SELECTIE_COLABORATORI
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.UTILAJ TO USER_LOGISTICA;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.PROGRAMARE_UTILAJE TO USER_LOGISTICA;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.COLABORATORI TO USER_LOGISTICA;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_SECURITATE.SELECTIE_COLABORATORI TO USER_LOGISTICA;

select * from ANGAJAT;